name: Test Application

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        
    - name: Install dependencies
      run: |
        cd apps/web
        pnpm install
        
    - name: Run TypeScript typecheck
      run: |
        cd apps/web
        pnpm typecheck
        
    - name: Run linting
      run: |
        cd apps/web
        pnpm lint
        
    - name: Run tests
      run: |
        cd apps/web
        pnpm test --run
        
    - name: Build application
      run: |
        cd apps/web
        pnpm build

  test-backend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        cd apps/api
        pip install -r requirements.txt
        
    - name: Run Python linting
      run: |
        cd apps/api
        python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Run Python tests
      run: |
        cd apps/api
        python -m pytest tests/ -v
        
    - name: Test API startup
      run: |
        cd apps/api
        python -c "
        import sys
        sys.path.append('.')
        from dealbase_api.main import app
        from fastapi.testclient import TestClient
        client = TestClient(app)
        response = client.get('/api/health')
        assert response.status_code == 200
        print('API health check passed')
        "

  test-integration:
    runs-on: ubuntu-latest
    needs: [test-frontend, test-backend]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install frontend dependencies
      run: |
        cd apps/web
        pnpm install
        
    - name: Install backend dependencies
      run: |
        cd apps/api
        pip install -r requirements.txt
        
    - name: Start backend server
      run: |
        cd apps/api
        python -m uvicorn dealbase_api.main:app --host 0.0.0.0 --port 8000 &
        sleep 10
        
    - name: Test API endpoints
      run: |
        curl -f http://localhost:8000/api/health || exit 1
        curl -f http://localhost:8000/api/deals || exit 1
        echo "API endpoints are working"
        
    - name: Start frontend server
      run: |
        cd apps/web
        pnpm dev --port 3001 &
        sleep 15
        
    - name: Test frontend
      run: |
        curl -f http://localhost:3001/ || exit 1
        curl -f http://localhost:3001/deals || exit 1
        echo "Frontend is working"
        
    - name: Test frontend-backend integration
      run: |
        # Test that frontend can reach backend through Next.js API routes
        curl -f http://localhost:3001/api/deals || exit 1
        echo "Frontend-backend integration is working"
